services:
  db:
    image: postgres:18-alpine
    container_name: drive-clone-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: drive-clone-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit
    container_name: driveclone-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  pg_data:
  redis_data:
