export const ErrorCodes = {
  // Generic
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",

  // File / Folder
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FOLDER_NOT_FOUND: "FOLDER_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",

  // Storage / Quota
  INSUFFICIENT_STORAGE: "INSUFFICIENT_STORAGE",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",

  // Permissions / Sharing
  PERMISSION_DENIED: "PERMISSION_DENIED",
  SHARE_NOT_FOUND: "SHARE_NOT_FOUND",
  INVALID_SHARE_LINK: "INVALID_SHARE_LINK",
  SHARE_LINK_EXPIRED: "SHARE_LINK_EXPIRED",
  CANNOT_SHARE_WITH_OWNER: "CANNOT_SHARE_WITH_OWNER",

  // Upload
  UPLOAD_SESSION_NOT_FOUND: "UPLOAD_SESSION_NOT_FOUND",
  UPLOAD_SESSION_EXPIRED: "UPLOAD_SESSION_EXPIRED",
  CHUNK_ALREADY_UPLOADED: "CHUNK_ALREADY_UPLOADED",
  INVALID_CHUNK_INDEX: "INVALID_CHUNK_INDEX",

  // Trash
  RESOURCE_ALREADY_TRASHED: "RESOURCE_ALREADY_TRASHED",
  RESOURCE_NOT_IN_TRASH: "RESOURCE_NOT_IN_TRASH",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
